### ISSUE TITLE
BigPicture assets not updating with version 1.2.0

### ISSUE THREAD

**Issue by FanderWasTaken** [SteamGridDB/SGDBoop#22]
When trying to boop a horizontal grid for a game, everything seems like it's all working, but when launching into Steam's BP mode I still see the game's icon and a generic name for it. The only thing I found in log file was this:
```
Fri Aug 26 08:34:49 2022
Could not find ModInstallPath (either in regedit or registry.vdf) [97]
```
Running Windows 11 and latest stable Steam client (same issue is present in current beta version of Steam)

**Comment by mpaterakis** [comment]
Thanks a ton for the report! Fixed in 3705f87860ec4e590c6bfdf6347a1e9852071252

**Comment by meghprkh** [comment]
I am still having this issue after installing it from flathub on the steam deck (which seems to be v1.2.6). I could succesfully launch the test popup using `xdg-open sgdb://boop/test`. It also warns about 

```
(deck@steamdeck ~)$ flatpak list |  grep -i boop
SGDBoop com.steamgriddb.SGDBoop 1.2.6   stable  system

(deck@steamdeck ~)$ xdg-open sgdb://boop/test
(deck@steamdeck ~)$ Gtk-Message: 18:16:48.922: Failed to load module "canberra-gtk-module"

(deck@steamdeck ~)$ cat /home/deck/.local/state/sgdboop_error.log 
Sun Sep 11 17:39:21 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Sun Sep 11 17:39:26 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Sun Sep 11 17:39:53 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Sun Sep 11 17:46:52 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Sun Sep 11 17:47:27 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Sun Sep 11 17:47:54 2022
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

```
